/* KS Calculator v2 — clearer bilingual field calculator */
(function(){
const P={
 thermo:{ku:'سێرمۆ',en:'Thermoplastic',rate:4.00,beads:.45,waste:5,note:'خەمڵاندنی سەرەتایی بۆ ئەستووری نزیکەی 2 mm. نرخە ڕاستەقینەکە لە TDS/Specification وەربگرە.'},
 coldAcrylic:{ku:'بۆیاخی سارد ئەکریلیک',en:'Cold Acrylic',rate:.60,beads:.35,waste:5,note:'بۆ thin-film. نرخ بە پێی solids، ئەستووری و بەرهەم دەگۆڕێت.'},
 waterAcrylic:{ku:'ئەکریلیکی بنەمای ئاو',en:'Water-Based Acrylic',rate:.60,beads:.35,waste:5,note:'بۆ thin-film. TDS ـی بەرهەم سەرچاوەی کۆتاییە.'},
 mma:{ku:'پلاستیکی سارد / MMA',en:'MMA / Cold Plastic',rate:3.00,beads:.45,waste:5,note:'ڕێژەی hardener/catalyst لە TDS ـی هەمان بەرهەمەوە وەربگرە.'},
 twoK:{ku:'بۆیاخی دوو کۆمپۆنێت',en:'2K / Two Component',rate:.60,beads:.35,waste:5,note:'ڕێژەی Base + Hardener بە پێی TDS داخڵ بکە؛ preset تەنها بۆ خەمڵاندنە.'}
};
const SF={smoothAsphalt:{ku:'ئاسفاڵتی نەرم / نوێ',en:'Smooth Asphalt',f:1},roughAsphalt:{ku:'ئاسفاڵتی زبر / کۆن',en:'Rough Asphalt',f:1.10},concrete:{ku:'کۆنکریت',en:'Concrete',f:1.08},pavers:{ku:'کەلەبستۆن / بەردی ڕێگا',en:'Pavers / Cobblestone',f:1.20}};
const bi=(ku,en)=>`${ku}<small style="display:block;color:var(--muted);font-size:9px;margin-top:3px;direction:ltr">${en}</small>`;
const field=(label,id,value,step='.01',extra='')=>`<div class="field"><label>${label}</label><input class="ltr" id="${id}" type="number" min="0" step="${step}" value="${value}" ${extra}></div>`;
function result(label,val,unit=''){return `<div class="result"><span>${label}</span><b>${Number(val||0).toFixed(2)} ${unit}</b></div>`}
window.calcTool=function(){let t=document.querySelector('#toolBody');t.innerHTML=`<section class="kscalc-head"><b>هەژمارکەری کاری شەقام</b><small>Road Marking Calculator</small><p>یەکەم جۆری کار هەڵبژێرە، پاشان تەنها پێوانەکان داخڵ بکە. ئەنجامەکان خۆکار نوێ دەبنەوە.</p></section><div class="panel"><div class="tool-tabs"><button class="chip active" data-calc="coverage">ڕووبەر و ماددە</button><button class="chip" data-calc="line">هێڵی بەردەوام</button><button class="chip" data-calc="broken">هێڵی پچڕاو</button><button class="chip" data-calc="zebra">زێبرا</button><button class="chip" data-calc="mix">تێکەڵکردنی 2K</button></div><div id="calcBody"></div></div>`;document.querySelectorAll('[data-calc]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-calc]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderCalc(b.dataset.calc)});renderCalc('coverage')};
window.renderCalc=function(type){let c=document.querySelector('#calcBody');if(!c)return;
 if(type==='coverage'){c.innerHTML=`<div class="kscalc-guide"><b>١. ڕووبەرەکە بنووسە</b><span>٢. جۆری بۆیاخ هەڵبژێرە</span><span>٣. بڕی ماددە خۆکار دەردەچێت</span></div><div class="form-grid kscalc-form"><div class="field"><label>${bi('جۆری بۆیاخ','Paint Type')}</label><select id="paintType" onchange="syncCoverageDefaults();doCoverageCalc()">${Object.entries(P).map(([k,p])=>`<option value="${k}">${p.ku} — ${p.en}</option>`).join('')}</select></div><div class="field"><label>${bi('ڕووی شەقام','Road Surface')}</label><select id="surfaceType" onchange="doCoverageCalc()">${Object.entries(SF).map(([k,s])=>`<option value="${k}">${s.ku} — ${s.en}</option>`).join('')}</select></div>${field(bi('ڕووبەری کار (m²)','Work Area'),'workArea',100,'1','oninput="doCoverageCalc()"')}${field(bi('ڕێژەی بۆیاخ (kg/m²)','Paint Consumption'),'coverageRate',4,'.01','oninput="doCoverageCalc()"')}${field(bi('دانی شووشەیی (kg/m²)','Glass Beads'),'coverageBeads',.45,'.01','oninput="doCoverageCalc()"')}${field(bi('زیادەی کار (%)','Waste Allowance'),'coverageWaste',5,'.5','oninput="doCoverageCalc()"')}</div><div class="results" id="calcResults"></div><div class="kscalc-note" id="coverageNote"></div>`;syncCoverageDefaults();doCoverageCalc();return}
 if(type==='line'){c.innerHTML=`<div class="kscalc-guide"><b>هێڵی بەردەوام</b><span>درێژی × پانی = ڕووبەر</span></div><div class="form-grid kscalc-form">${field(bi('درێژی (m)','Length'),'l',1000,'1','oninput="doLineCalc()"')}${field(bi('پانی (cm)','Width'),'w',15,'.1','oninput="doLineCalc()"')}${field(bi('ڕێژەی ماددە (kg/m²)','Material Rate'),'r',4,'.01','oninput="doLineCalc()"')}${field(bi('دانی شووشەیی (kg/m²)','Glass Beads'),'g',.45,'.01','oninput="doLineCalc()"')}${field(bi('زیادەی کار (%)','Waste Allowance'),'x',5,'.5','oninput="doLineCalc()"')}</div><div class="results" id="calcResults"></div><div id="addProject"></div>`;doLineCalc();return}
 if(type==='broken'){c.innerHTML=`<div class="kscalc-guide"><b>هێڵی پچڕاو</b><span>Mark = بەشی بۆیاخکراو</span><span>Gap = بۆشایی نێوان هێڵەکان</span></div><div class="form-grid kscalc-form">${field(bi('کۆی درێژی (m)','Total Length'),'bl',1000,'1','oninput="doBrokenCalc()"')}${field(bi('درێژی هەر هێڵ (m)','Mark Length'),'bm',3,'.1','oninput="doBrokenCalc()"')}${field(bi('بۆشایی (m)','Gap Length'),'bg',9,'.1','oninput="doBrokenCalc()"')}${field(bi('پانی (cm)','Width'),'bw',15,'.1','oninput="doBrokenCalc()"')}${field(bi('ڕێژەی ماددە (kg/m²)','Material Rate'),'br',4,'.01','oninput="doBrokenCalc()"')}${field(bi('دانی شووشەیی (kg/m²)','Glass Beads'),'bb',.45,'.01','oninput="doBrokenCalc()"')}${field(bi('زیادەی کار (%)','Waste Allowance'),'bx',5,'.5','oninput="doBrokenCalc()"')}</div><div class="results" id="calcResults"></div>`;doBrokenCalc();return}
 if(type==='zebra'){c.innerHTML=`<div class="kscalc-guide"><b>پەڕینەوەی زێبرا</b><span>ژمارە × پانی × درێژی = ڕووبەر</span></div><div class="form-grid kscalc-form">${field(bi('ژمارەی هێڵەکان','Number of Stripes'),'zn',8,'1','oninput="doZebraCalc()"')}${field(bi('پانی هەر هێڵ (m)','Stripe Width'),'zw',.5,'.01','oninput="doZebraCalc()"')}${field(bi('درێژی هەر هێڵ (m)','Stripe Length'),'zl',4,'.01','oninput="doZebraCalc()"')}${field(bi('ڕێژەی ماددە (kg/m²)','Material Rate'),'zr',4,'.01','oninput="doZebraCalc()"')}${field(bi('دانی شووشەیی (kg/m²)','Glass Beads'),'zb',.45,'.01','oninput="doZebraCalc()"')}${field(bi('زیادەی کار (%)','Waste Allowance'),'zx',5,'.5','oninput="doZebraCalc()"')}</div><div class="results" id="calcResults"></div>`;doZebraCalc();return}
 c.innerHTML=`<div class="kscalc-guide"><b>تێکەڵکردنی 2K</b><span>ڕێژەکە لە TDS ـی بەرهەمەکەت وەربگرە</span></div><div class="form-grid kscalc-form">${field(bi('کۆی تێکەڵ (kg)','Total Mix'),'mt',100,'.1','oninput="doMixCalc()"')}${field(bi('بەشی بنەڕەت','Base Parts'),'mp',98,'.1','oninput="doMixCalc()"')}${field(bi('بەشی هاردنەر','Hardener Parts'),'mh',2,'.1','oninput="doMixCalc()"')}</div><div class="results" id="calcResults"></div><div class="kscalc-note">98:2 تەنها نموونەی هەژمارە؛ بۆ کارکردن ڕێژەی نووسراو لە TDS بەکاربهێنە.</div>`;doMixCalc()};
window.syncCoverageDefaults=function(){let p=P[document.querySelector('#paintType')?.value]||P.thermo;let r=document.querySelector('#coverageRate'),b=document.querySelector('#coverageBeads'),w=document.querySelector('#coverageWaste');if(r)r.value=p.rate;if(b)b.value=p.beads;if(w)w.value=p.waste};
window.doCoverageCalc=function(){let p=P[document.querySelector('#paintType')?.value]||P.thermo,s=SF[document.querySelector('#surfaceType')?.value]||SF.smoothAsphalt,A=Math.max(0,num('workArea')),base=Math.max(0,num('coverageRate')),rate=base*s.f,bead=Math.max(0,num('coverageBeads')),w=Math.max(0,num('coverageWaste')),net=A*rate,paint=net*(1+w/100),beads=A*bead*(1+w/100),bags25=paint/25;document.querySelector('#calcResults').innerHTML=result(bi('ڕووبەر','Area'),A,'m²')+result(bi('بۆیاخی پێویست + زیادە','Paint + Waste'),paint,'kg')+result(bi('دانی شووشەیی + زیادە','Glass Beads + Waste'),beads,'kg')+result(bi('ژمارەی کیسە/قوطی 25kg','25 kg Packs'),Math.ceil(bags25),'')+result(bi('نرخی کاریگەر','Adjusted Rate'),rate,'kg/m²');document.querySelector('#coverageNote').innerHTML=`<b>${p.ku} — ${p.en}</b><br>${p.note}<br>فاکتەری ڕوو: <b>${s.f.toFixed(2)}</b>. ئەگەر TDS نرخێکی جیاواز دەڵێت، لە خانەی «ڕێژەی بۆیاخ» ئەو نرخە داخڵ بکە.`};
window.doLineCalc=function(){let A=num('l')*num('w')/100,M=A*num('r'),G=A*num('g'),P=M*(1+num('x')/100),GB=G*(1+num('x')/100);document.querySelector('#calcResults').innerHTML=result(bi('ڕووبەر','Area'),A,'m²')+result(bi('ماددەی خاو','Net Material'),M,'kg')+result(bi('ماددە + زیادە','Material + Waste'),P,'kg')+result(bi('دانی شووشەیی + زیادە','Glass Beads + Waste'),GB,'kg');let a=document.querySelector('#addProject');if(a)a.innerHTML=`<button class="btn small" style="margin-top:10px" onclick="addProjectItem('هێڵی بەردەوام',${A},${P},${GB})">+ زیادکردن بۆ پڕۆژە</button>`};
window.doBrokenCalc=function(){let L=num('bl'),m=num('bm'),g=num('bg'),cycle=m+g,paint=cycle>0?Math.floor(L/cycle)*m+Math.min(L%cycle,m):0,A=paint*num('bw')/100,M=A*num('br'),B=A*num('bb'),w=num('bx');document.querySelector('#calcResults').innerHTML=result(bi('درێژی بۆیاخکراو','Painted Length'),paint,'m')+result(bi('ڕووبەر','Area'),A,'m²')+result(bi('ماددە + زیادە','Material + Waste'),M*(1+w/100),'kg')+result(bi('دانی شووشەیی + زیادە','Glass Beads + Waste'),B*(1+w/100),'kg')};
window.doZebraCalc=function(){let A=num('zn')*num('zw')*num('zl'),M=A*num('zr'),B=A*num('zb'),w=num('zx');document.querySelector('#calcResults').innerHTML=result(bi('ڕووبەری ڕاستەقینە','Actual Area'),A,'m²')+result(bi('ماددە + زیادە','Material + Waste'),M*(1+w/100),'kg')+result(bi('دانی شووشەیی + زیادە','Glass Beads + Waste'),B*(1+w/100),'kg')};
window.doMixCalc=function(){let T=num('mt'),p=num('mp'),h=num('mh'),sum=p+h,base=sum?T*p/sum:0,hard=sum?T*h/sum:0;document.querySelector('#calcResults').innerHTML=result(bi('ماددەی بنەڕەت','Base'),base,'kg')+result(bi('هاردنەر','Hardener'),hard,'kg')};
const st=document.createElement('style');st.textContent=`.kscalc-head{border:1px solid #554916;background:linear-gradient(135deg,#171912,#0c0d0d);border-radius:20px;padding:16px;margin-bottom:10px}.kscalc-head>b{display:block;font-size:18px}.kscalc-head>small{display:block;color:var(--yellow);direction:ltr;text-align:right;margin-top:3px}.kscalc-head p{font-size:10px;color:var(--muted);line-height:1.8;margin:8px 0 0}.kscalc-guide{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0}.kscalc-guide>*{background:#171919;border:1px solid var(--line);border-radius:999px;padding:7px 10px;font-size:9px}.kscalc-guide b{background:#292500;color:var(--yellow);border-color:#5d500d}.kscalc-form .field{background:#111313;border:1px solid var(--line);border-radius:14px;padding:10px}.kscalc-form label{font-weight:800;line-height:1.5}.kscalc-form input,.kscalc-form select{margin-top:7px}.kscalc-note{margin-top:12px;padding:12px;border-radius:13px;background:#111313;border-right:3px solid var(--yellow);font-size:10px;color:var(--muted);line-height:1.9}.kscalc-note b{color:var(--text)}.results .result span small{font-weight:400}@media(max-width:650px){.kscalc-form{grid-template-columns:1fr 1fr}.kscalc-form .field{padding:9px}.kscalc-form label{font-size:10px}}`;document.head.appendChild(st);
})();