const materials=[
{name:'بۆیاخ',unit:'سەتڵ/قوتو'},
{name:'گڵاسپید',unit:'kg'},
{name:'هاردنەر',unit:'kg'},
{name:'تەنەر',unit:'L'},
{name:'تیپ',unit:'دانە'},
{name:'ڕۆڵە',unit:'دانە'},
{name:'فڵچە',unit:'دانە'},
{name:'گاز',unit:'L'},
{name:'بەنزین',unit:'L'},
{name:'گریس',unit:'kg'},
{name:'غاز',unit:'L'}
];
const units=['kg','L','دانە','ڕۆڵ','سەتڵ/قوتو','کیسە'];
const statusText={draft:'پاشەکەوتکراو',submitted:'چاوەڕێی پەسەند',approved:'پەسەندکراو',returned:'گەڕێندراوەتەوە'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let editingId=null,approvalRecordId=null,editUnlockedUntil=0,pendingPinAction=null;
function materialRows(){ $('#materialList').innerHTML='';materials.forEach((m,i)=>{const r=document.createElement('div');r.className='material-row';r.innerHTML=`<div class="material-name">${m.name}</div><input type="number" step="0.01" min="0" name="mat-${i}" placeholder="بڕ"><select name="unit-${i}">${units.map(u=>`<option${u===m.unit?' selected':''}>${u}</option>`).join('')}</select>`;$('#materialList').appendChild(r)})} materialRows();
const dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open('sulaimani-road-team',2);req.onupgradeneeded=e=>{const db=e.target.result;if(!db.objectStoreNames.contains('records')){const s=db.createObjectStore('records',{keyPath:'id'});s.createIndex('date','date');s.createIndex('status','status')}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
async function allRecords(){const db=await dbPromise;return new Promise((res,rej)=>{const r=db.transaction('records').objectStore('records').getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>(b.date||'').localeCompare(a.date||'')||b.createdAt-a.createdAt));r.onerror=()=>rej(r.error)})}
async function getRecord(id){const db=await dbPromise;return new Promise((res,rej)=>{const r=db.transaction('records').objectStore('records').get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putRecord(v){const db=await dbPromise;return new Promise((res,rej)=>{const r=db.transaction('records','readwrite').objectStore('records').put(v);r.onsuccess=()=>res(v);r.onerror=()=>rej(r.error)})}
async function deleteRecord(id){const db=await dbPromise;return new Promise((res,rej)=>{const r=db.transaction('records','readwrite').objectStore('records').delete(id);r.onsuccess=res;r.onerror=()=>rej(r.error)})}
async function hashPin(pin){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(pin));return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('')}
const pinKey=r=>`srt-pin-${r}`; async function verifyPin(r,p){const s=localStorage.getItem(pinKey(r));return s? s===await hashPin(p):null}
function openPin(title,help,action){$('#pinTitle').textContent=title;$('#pinHelp').textContent=help;$('#pinInput').value='';pendingPinAction=action;$('#pinModal').classList.remove('hidden')}
async function setPin(role,label){openPin(`دانانی ${label}`,'کۆدێکی نوێی لانیکەم ٤ ژمارە دابنێ.',async p=>{if(p.length<4){alert('لانیکەم ٤ ژمارە');return false}localStorage.setItem(pinKey(role),await hashPin(p));alert('کۆدەکە دانرا');return true})}
function closeModal(id){$('#'+id).classList.add('hidden')} $$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
$('#pinConfirm').onclick=async()=>{const p=$('#pinInput').value.trim();if(!p)return;const ok=await pendingPinAction?.(p);if(ok!==false)closeModal('pinModal')};
function editIsUnlocked(){return Date.now()<editUnlockedUntil} function setEditState(open){editUnlockedUntil=open?Date.now()+10*60*1000:0;const u=editIsUnlocked();$('#workFields').disabled=!u;$('#editLockBadge').textContent=u?'🔓 دەسەڵات کراوە':'🔒 پارێزراو';$('#editLockBadge').className='badge '+(u?'open':'locked');$('#unlockEdit').textContent=u?'🔒 داخستنی دەسەڵات':'🔑 دەسەڵاتی تۆمارکردن'}
$('#unlockEdit').onclick=()=>{if(editIsUnlocked())return setEditState(false);if(!localStorage.getItem(pinKey('admin')))return setPin('admin','کۆدی دەستکاری');openPin('کردنەوەی پەڕە','کۆدی دەستکاری بنووسە.',async p=>{if(await verifyPin('admin',p)){setEditState(true);return true}alert('کۆد هەڵەیە');return false})};
function today(){return new Date().toISOString().slice(0,10)} function nextRecordNo(date=today()){return `${date.replaceAll('-','')}-${String(Date.now()).slice(-4)}`}
function resetForm(){editingId=null;$('#workForm').reset();$('[name=date]').value=today();$('[name=recordNo]').value=nextRecordNo();materialRows();$('#approvalSummary').innerHTML=''} resetForm();setEditState(false);
$('#newDay').onclick=()=>{resetForm();$('#dailyPage').scrollIntoView({behavior:'smooth'});if(!editIsUnlocked())$('#unlockEdit').click()};
function collectMaterials(){return materials.map((m,i)=>({name:m.name,quantity:Number($(`[name="mat-${i}"]`).value||0),unit:$(`[name="unit-${i}"]`).value})).filter(x=>x.quantity>0)}
async function filesFromForm(fd){const out={};for(const k of ['photoBefore','photoDuring','photoAfter']){const f=fd.get(k);if(f&&f.size)out[k]={name:f.name,type:f.type,size:f.size,blob:f}}return out}
async function buildRecord(statusOverride){const fd=new FormData($('#workForm')),old=editingId?await getRecord(editingId):null,photos=await filesFromForm(fd);return{id:editingId||crypto.randomUUID(),recordNo:fd.get('recordNo')||nextRecordNo(fd.get('date')),date:fd.get('date'),startTime:fd.get('startTime'),endTime:fd.get('endTime'),location:fd.get('location'),type:fd.get('type'),paintType:fd.get('paintType'),color:fd.get('color'),length:Number(fd.get('length')||0),width:Number(fd.get('width')||0),area:Number(fd.get('area')||0),lat:fd.get('lat'),lng:fd.get('lng'),staff:fd.get('staff'),equipment:fd.get('equipment'),note:fd.get('note'),materials:collectMaterials(),photos:{...(old?.photos||{}),...photos},status:statusOverride||old?.status||'draft',approvals:statusOverride==='submitted'?[]:(old?.approvals||[]),createdAt:old?.createdAt||Date.now(),updatedAt:Date.now()}}
$('#workForm').onsubmit=async e=>{e.preventDefault();if(!editIsUnlocked())return alert('کۆدی دەسەڵات پێویستە');const r=await buildRecord();if(editingId&&r.status==='approved'){r.status='draft';r.approvals=[]}await putRecord(r);alert('پەڕەکە پارێزرا');resetForm();setEditState(false);await refresh()};
$('#submitApproval').onclick=async()=>{if(!editIsUnlocked())return alert('کۆدی دەسەڵات پێویستە');const r=await buildRecord('submitted');await putRecord(r);alert('پەڕەکە نێردرا بۆ پەسەندکردن');resetForm();setEditState(false);await refresh()};
$('#getGps').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{$('[name=lat]').value=p.coords.latitude.toFixed(6);$('[name=lng]').value=p.coords.longitude.toFixed(6)},()=>alert('ڕێگەپێدانی Location بپشکنە')):alert('GPS بەردەست نییە');
function showApproval(r){$('#approvalSummary').innerHTML=(r.approvals||[]).length?`<b>پەسەندکردن:</b> `+r.approvals.map(a=>`${a.role==='manager'?'بەڕێوەبەر':'سەرپەرشتیار'} — ${a.action==='approve'?'پەسەندکرا':'گەڕێندرایەوە'}`).join(' · '):''}
async function loadPage(id,needEdit=false){const r=await getRecord(id);if(!r)return;editingId=id;for(const k of ['recordNo','date','startTime','endTime','location','type','paintType','color','length','width','area','lat','lng','staff','equipment','note']){const el=$(`[name="${k}"]`);if(el)el.value=r[k]??''}materialRows();(r.materials||[]).forEach(x=>{const i=materials.findIndex(m=>m.name===x.name);if(i>=0){$(`[name="mat-${i}"]`).value=x.quantity;$(`[name="unit-${i}"]`).value=x.unit}});showApproval(r);$('#dailyPage').scrollIntoView({behavior:'smooth'});if(needEdit&&!editIsUnlocked())$('#unlockEdit').click()}
async function removeExisting(id){const go=async()=>{if(confirm('دڵنیایت لە سڕینەوەی ئەم پەڕەیە؟')){await deleteRecord(id);await refresh()}};if(editIsUnlocked())return go();if(!localStorage.getItem(pinKey('admin')))return setPin('admin','کۆدی دەستکاری');openPin('سڕینەوەی پەڕە','کۆدی دەستکاری بنووسە.',async p=>{if(await verifyPin('admin',p)){await go();return true}alert('کۆد هەڵەیە');return false})}
function openApproval(id){approvalRecordId=id;$('#approvalPin').value='';$('#approvalComment').value='';getRecord(id).then(r=>$('#approvalRecordTitle').textContent=`${r.date} — ${r.location||''}`);$('#approvalModal').classList.remove('hidden')}
async function approvalAction(action){const role=$('#approvalRole').value,p=$('#approvalPin').value.trim();if(!localStorage.getItem(pinKey(role))){closeModal('approvalModal');return setPin(role,role==='manager'?'کۆدی بەڕێوەبەر':'کۆدی سەرپەرشتیار')}if(!await verifyPin(role,p))return alert('کۆد هەڵەیە');const r=await getRecord(approvalRecordId);r.approvals=[...(r.approvals||[]),{role,action,comment:$('#approvalComment').value.trim(),at:Date.now()}];r.status=action==='return'?'returned':'approved';r.updatedAt=Date.now();await putRecord(r);closeModal('approvalModal');await refresh();alert(action==='return'?'پەڕەکە گەڕێندرایەوە':'پەڕەکە پەسەند کرا')}
$('#approveBtn').onclick=()=>approvalAction('approve');$('#returnBtn').onclick=()=>approvalAction('return');
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function renderRecords(filter=''){const all=await allRecords(),q=filter.trim().toLowerCase(),rs=all.filter(r=>!q||[r.date,r.recordNo,r.location,r.type,r.paintType,statusText[r.status]].join(' ').toLowerCase().includes(q));$('#recordList').innerHTML=rs.length?'':'<p>هێشتا پەڕەیەک تۆمار نەکراوە.</p>';rs.forEach(r=>{const d=document.createElement('div');d.className='record-card';d.innerHTML=`<div class="record-top"><h4>📅 ${esc(r.date)} — ${esc(r.location||'شوێن دیاری نەکراوە')}</h4><span class="status ${r.status}">${statusText[r.status]}</span></div><div class="record-meta"><span>${esc(r.recordNo)}</span><span>${esc(r.type)}</span><span>${Number(r.length||0).toFixed(1)} m</span><span>${Number(r.area||0).toFixed(1)} m²</span></div><div class="record-actions"><button data-view="${r.id}">بینینی پەڕە</button><button data-edit="${r.id}">دەستکاری</button>${r.status==='submitted'||r.status==='returned'?`<button data-approve="${r.id}">پەسەند / گەڕاندنەوە</button>`:''}<button class="delete" data-delete="${r.id}">سڕینەوە</button></div>`;$('#recordList').appendChild(d)});$$('[data-view]').forEach(b=>b.onclick=()=>loadPage(b.dataset.view));$$('[data-edit]').forEach(b=>b.onclick=()=>loadPage(b.dataset.edit,true));$$('[data-approve]').forEach(b=>b.onclick=()=>openApproval(b.dataset.approve));$$('[data-delete]').forEach(b=>b.onclick=()=>removeExisting(b.dataset.delete))}
$('#recordSearch').oninput=e=>renderRecords(e.target.value);
async function renderStats(){const r=await allRecords();$('#statRecords').textContent=r.length;$('#statLength').textContent=r.reduce((s,x)=>s+Number(x.length||0),0).toFixed(1);$('#statArea').textContent=r.reduce((s,x)=>s+Number(x.area||0),0).toFixed(1);$('#statApproved').textContent=r.filter(x=>x.status==='approved').length}
async function refresh(){await renderRecords($('#recordSearch').value);await renderStats()} refresh();
$('#setAdminPin').onclick=()=>setPin('admin','کۆدی دەستکاری');$('#setSupervisorPin').onclick=()=>setPin('supervisor','کۆدی سەرپەرشتیار');$('#setManagerPin').onclick=()=>setPin('manager','کۆدی بەڕێوەبەر');$('#printPage').onclick=()=>window.print();
const a=$('#assistant');$('#assistantBtn').onclick=()=>a.classList.remove('hidden');$('#closeAssistant').onclick=()=>a.classList.add('hidden');function addMsg(t,c){const d=document.createElement('div');d.className='msg '+c;d.textContent=t;$('#chat').appendChild(d)}$('#sendChat').onclick=()=>{const i=$('#chatInput'),q=i.value.trim();if(!q)return;addMsg(q,'user');i.value='';setTimeout(()=>addMsg('یاریدەدەری AI لە هەنگاوی backend بە شێوەی پارێزراو پەیوەست دەکرێت.','bot'),200)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');