(()=>{
let sb=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ensureStyle(){if(document.querySelector('#approvalAdminStyle'))return;const s=document.createElement('style');s.id='approvalAdminStyle';s.textContent=`#rdApprovalPanel{display:block!important}.approval-admin-head{display:flex;justify-content:space-between;align-items:center;gap:8px;flex-wrap:wrap}.approval-admin-count{background:#fff3cd;color:#7a4a12;border-radius:999px;padding:6px 10px;font-weight:900}.approval-admin-row{border:1px solid #d9e0e5;border-radius:12px;padding:11px;margin:9px 0;background:#fff}.approval-admin-name{font-size:17px;font-weight:900}.approval-admin-email{direction:ltr;text-align:right;overflow-wrap:anywhere}.approval-admin-meta{font-size:12px;color:#6d7780;margin-top:4px}.approval-admin-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:9px}.approval-admin-actions button{flex:1;min-width:140px;border:0;border-radius:9px;padding:10px;font-weight:900}.approval-admin-approve{background:#16753a;color:#fff}.approval-admin-reject{background:#a32626;color:#fff}.approval-admin-empty{padding:10px;border:1px dashed #ccd5db;border-radius:10px;background:#fafcfd;color:#66747e}`;document.head.appendChild(s);}
function ensurePanel(){const modal=document.querySelector('#rdAdminModal .role-admin-modal-card');if(!modal)return null;let root=document.querySelector('#rdApprovalPanel');if(!root){root=document.createElement('div');root.id='rdApprovalPanel';root.className='admin-fixed-section';const head=modal.querySelector('.role-admin-modal-head');if(head?.nextSibling)modal.insertBefore(root,head.nextSibling);else modal.appendChild(root);}root.style.display='block';if(!document.querySelector('#approvalAdminBox'))root.innerHTML='<div id="approvalAdminBox"><div class="approval-admin-head"><h3>✅ داواکارییەکانی چوونەژوورەوە</h3><span id="approvalAdminCount" class="approval-admin-count">0</span></div><p>بەکارهێنەری نوێ تا پەسەندی Admin نەبێت ناچێتە ناو ئەپەکە.</p><div id="approvalAdminList"></div></div>';return root;}
async function getClient(){if(window.teamPaintServer?.client)return window.teamPaintServer.client;for(let i=0;i<40;i++){await new Promise(r=>setTimeout(r,250));if(window.teamPaintServer?.client)return window.teamPaintServer.client;}return null;}
async function load(){if(window.teamPaintAdminSensitiveUnlocked!==true)return;ensureStyle();if(!ensurePanel())return;sb=sb||await getClient();const list=document.querySelector('#approvalAdminList'),count=document.querySelector('#approvalAdminCount');if(!sb){if(list)list.innerHTML='<div class="approval-admin-empty">پەیوەندی بە سێرڤەر دروست نەبوو.</div>';return;}const {data:{user}}=await sb.auth.getUser();if(!user){list.innerHTML='<div class="approval-admin-empty">هەژماری Admin پەیوەست نییە.</div>';return;}const {data:me}=await sb.from('profiles').select('role').eq('id',user.id).maybeSingle();if(me?.role!=='admin'){list.innerHTML='<div class="approval-admin-empty">ئەم هەژمارە Admin نییە.</div>';return;}const {data,error}=await sb.from('device_installs').select('install_id,full_name,email,approval_status,display_mode,device_info,first_seen,last_seen').neq('approval_status','approved').order('first_seen',{ascending:false});if(error){list.innerHTML='<div class="approval-admin-empty">هەڵە لە خوێندنەوەی داواکارییەکان.</div>';return;}const rows=data||[];count.textContent=rows.length;list.innerHTML=rows.length?rows.map(x=>{const info=x.device_info||{};const rejected=x.approval_status==='rejected';return `<div class="approval-admin-row"><div class="approval-admin-name">${esc(x.full_name)}</div><div class="approval-admin-email">${esc(x.email)}</div><div class="approval-admin-meta">${rejected?'⛔ ڕەتکراوە':'⏳ چاوەڕێی پەسەند'} · ${x.display_mode==='standalone'?'📲 دامەزراو':'🌐 براوزەر'} · ${esc(info.platform||'')}</div><div class="approval-admin-actions"><button class="approval-admin-approve" data-a="${x.install_id}">✅ پەسەندکردن</button>${rejected?'':`<button class="approval-admin-reject" data-r="${x.install_id}">⛔ ڕەتکردنەوە</button>`}</div></div>`}).join(''):'<div class="approval-admin-empty">هیچ داواکارییەکی چاوەڕێ نییە.</div>';document.querySelectorAll('#approvalAdminList [data-a]').forEach(b=>b.onclick=()=>setStatus(b.dataset.a,'approved'));document.querySelectorAll('#approvalAdminList [data-r]').forEach(b=>b.onclick=()=>setStatus(b.dataset.r,'rejected'));}
async function setStatus(id,status){if(!confirm(status==='approved'?'ئەم بەکارهێنەرە پەسەند بکرێت؟':'ئەم بەکارهێنەرە ڕەت بکرێتەوە؟'))return;sb=sb||await getClient();if(!sb)return alert('پەیوەندی بە سێرڤەر نییە.');const {error}=await sb.rpc('admin_set_device_approval',{target_install:id,new_status:status});if(error)return alert('گۆڕانکاری سەرکەوتوو نەبوو.');alert(status==='approved'?'بەکارهێنەر پەسەندکرا ✅':'داواکاری ڕەتکرایەوە ⛔');await load();window.dispatchEvent(new CustomEvent('team-paint-admin-unlocked'));}
function clear(){const root=document.querySelector('#rdApprovalPanel');if(root)root.innerHTML='';}
async function init(){ensureStyle();sb=await getClient();window.addEventListener('team-paint-admin-unlocked',()=>setTimeout(()=>load().catch(console.error),50));window.addEventListener('team-paint-admin-locked',clear);setInterval(()=>{if(!document.hidden&&window.teamPaintAdminSensitiveUnlocked===true)load().catch(()=>{})},5000);if(window.teamPaintAdminSensitiveUnlocked===true)load().catch(()=>{});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();