(()=>{
const wait=()=>window.teamPaintServer?.client&&window.teamPaintDevice?install():setTimeout(wait,300);
let watchId=null,map=null,markers=new Map(),pollTimer=null,lastHistoryAt=0,lastHistoryPos=null,isAdminUser=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const distanceM=(a,b)=>{if(!a||!b)return Infinity;const R=6371000,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x));};
function injectStyle(){const s=document.createElement('style');s.textContent=`.live-gps{margin:14px 0;padding:14px;border:1px solid #d6dbe0;border-radius:16px;background:#fff}.live-gps h2{margin:0 0 4px}.live-gps-head{display:flex;gap:8px;align-items:center;justify-content:space-between;flex-wrap:wrap}.live-gps-actions{display:flex;gap:8px;flex-wrap:wrap}.live-gps-status{font-weight:800;padding:8px 0}.live-gps-status.on{color:#16753a}.live-gps-status.off{color:#8b5d00}#teamLiveMap{height:420px;border-radius:14px;overflow:hidden;background:#eef1f4;margin-top:10px}.team-live-list{display:grid;gap:8px;margin-top:10px}.team-live-card{border:1px solid #e0e4e7;border-radius:12px;padding:10px;background:#fafbfc}.team-live-meta{font-size:12px;opacity:.75;margin-top:3px}.member-gps-only #teamLiveMap,.member-gps-only #teamLiveList,.member-gps-only #liveGpsRefresh{display:none!important}@media(max-width:600px){#teamLiveMap{height:330px}}`;document.head.appendChild(s);}
function injectUi(){const main=document.querySelector('main');if(!main||document.querySelector('#liveGpsSection'))return;const section=document.createElement('section');section.id='liveGpsSection';section.className='live-gps';section.innerHTML=`<div class="live-gps-head"><div><h2>🛰️ GPS ـی ڕاستەوخۆی تیم</h2><small id="liveGpsHelp">شوێنی تیم لەکاتی کاردا</small></div><div class="live-gps-actions"><button id="liveGpsStart" class="primary" type="button">▶️ دەستپێکردنی Live GPS</button><button id="liveGpsStop" class="danger" type="button">⏹ کۆتایی GPS</button><button id="liveGpsRefresh" class="secondary" type="button">🔄 نوێکردنەوە</button></div></div><div id="liveGpsStatus" class="live-gps-status off">GPS ناچالاکە</div><div id="teamLiveMap"></div><div id="teamLiveList" class="team-live-list"></div>`;const anchor=document.querySelector('.archive')||main.lastElementChild;main.insertBefore(section,anchor);}
function status(t,on=false){const e=document.querySelector('#liveGpsStatus');if(e){e.textContent=t;e.className='live-gps-status '+(on?'on':'off');}}
async function getAdmin(sb){const {data:{user}}=await sb.auth.getUser();if(!user)return null;const {data}=await sb.from('profiles').select('id,full_name,role').eq('id',user.id).maybeSingle();return data?.role==='admin'?{user,profile:data}:null;}
async function publishMember(p){const c=p.coords,now=Date.now(),pos={lat:c.latitude,lng:c.longitude},append=now-lastHistoryAt>=30000||distanceM(lastHistoryPos,pos)>=15;await window.teamPaintDevice.api('location',{latitude:c.latitude,longitude:c.longitude,accuracy_m:Number.isFinite(c.accuracy)?c.accuracy:null,speed_mps:Number.isFinite(c.speed)?c.speed:null,heading_deg:Number.isFinite(c.heading)?c.heading:null,append_history:append});if(append){lastHistoryAt=now;lastHistoryPos=pos;}status(`🟢 GPS چالاکە — دوا نوێکردنەوە: ${new Date().toLocaleTimeString('ckb-IQ')}`,true);}
async function publishAdmin(sb,admin,p){const c=p.coords,row={tracker_id:localStorage.getItem('team-paint-tracker-id')||crypto.randomUUID(),user_id:admin.user.id,team_name:`تیمی بۆیاخ — ${admin.profile.full_name||'Admin'}`,latitude:c.latitude,longitude:c.longitude,accuracy_m:Number.isFinite(c.accuracy)?c.accuracy:null,speed_mps:Number.isFinite(c.speed)?c.speed:null,heading_deg:Number.isFinite(c.heading)?c.heading:null,is_active:true,updated_at:new Date().toISOString()};localStorage.setItem('team-paint-tracker-id',row.tracker_id);await sb.from('live_team_locations').upsert(row,{onConflict:'tracker_id'});status(`🟢 GPS چالاکە — دوا نوێکردنەوە: ${new Date().toLocaleTimeString('ckb-IQ')}`,true);await renderAdmin(sb);}
async function startGps(sb,admin){if(!navigator.geolocation)return alert('GPS لەم ئامێرەدا بەردەست نییە.');if(watchId!==null)return alert('Live GPS پێشتر چالاکە.');if(!admin&&!window.teamPaintDevice.registered)return alert('سەرەتا ناو و ئیمەیڵەکەت تۆمار بکە.');status('داواکاری ڕێگەپێدانی Location...');watchId=navigator.geolocation.watchPosition(p=>(admin?publishAdmin(sb,admin,p):publishMember(p)).catch(e=>{console.error(e);status('هەڵە لە ناردنی GPS');}),()=>{if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;status('ڕێگەی Location نەدرا یان GPS بەردەست نییە');alert('ڕێگەپێدانی Location/GPS بپشکنە و Allow بکە.');},{enableHighAccuracy:true,maximumAge:5000,timeout:20000});}
async function stopGps(sb,admin){if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null;}if(admin){const id=localStorage.getItem('team-paint-tracker-id');if(id)await sb.from('live_team_locations').update({is_active:false,updated_at:new Date().toISOString()}).eq('tracker_id',id).eq('user_id',admin.user.id);}else if(window.teamPaintDevice.registered){await window.teamPaintDevice.api('stop_location').catch(()=>{});}status('⏹ GPS وەستێنرا');if(admin)await renderAdmin(sb);}
function ensureMap(){if(map||!window.L)return;map=L.map('teamLiveMap',{zoomControl:true}).setView([35.5613,45.4309],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);}
function ageText(ts){const s=Math.max(0,Math.round((Date.now()-new Date(ts).getTime())/1000));if(s<60)return `${s} چرکە پێش ئێستا`;return `${Math.round(s/60)} خولەک پێش ئێستا`;}
async function renderAdmin(sb){if(!isAdminUser)return;ensureMap();const list=document.querySelector('#teamLiveList');const [{data:a},{data:b}]=await Promise.all([sb.from('live_team_locations').select('*').order('updated_at',{ascending:false}),sb.from('device_live_locations').select('*').order('updated_at',{ascending:false})]);const rows=[...(a||[]).map(r=>({...r,key:'u-'+r.tracker_id,name:r.team_name})),...(b||[]).map(r=>({...r,key:'d-'+r.install_id,name:r.full_name?`تیمی بۆیاخ — ${r.full_name}`:'تیمی بۆیاخ'}))].sort((x,y)=>new Date(y.updated_at)-new Date(x.updated_at));const seen=new Set(),bounds=[];for(const r of rows){seen.add(r.key);const ll=[r.latitude,r.longitude];bounds.push(ll);let m=markers.get(r.key);const popup=`<b>${esc(r.name)}</b><br>${r.is_active?'🟢 چالاک':'⚪ وەستاو'}<br>${esc(ageText(r.updated_at))}`;if(!m){m=L.marker(ll).addTo(map);markers.set(r.key,m);}else m.setLatLng(ll);m.bindPopup(popup);}for(const [id,m] of markers){if(!seen.has(id)){map.removeLayer(m);markers.delete(id);}}if(bounds.length===1)map.setView(bounds[0],16);else if(bounds.length>1)map.fitBounds(bounds,{padding:[30,30],maxZoom:16});list.innerHTML=rows.length?rows.map(r=>`<div class="team-live-card"><b>${r.is_active?'🟢':'⚪'} ${esc(r.name)}</b><div class="team-live-meta">${esc(ageText(r.updated_at))} · دقت: ${Math.round(r.accuracy_m||0)} m</div><div class="team-live-meta">${Number(r.latitude).toFixed(6)}, ${Number(r.longitude).toFixed(6)}</div></div>`).join(''):'<div class="team-live-card">هێشتا هیچ تیمێک Live GPS ـی دەست پێنەکردووە.</div>';}
async function install(){injectStyle();injectUi();const sb=window.teamPaintServer.client,admin=await getAdmin(sb);isAdminUser=!!admin;if(!admin){document.querySelector('#liveGpsSection').classList.add('member-gps-only');document.querySelector('#liveGpsHelp').textContent='تەنها شوێنی خۆت بۆ Admin دەنێردرێت';}document.querySelector('#liveGpsStart').onclick=()=>startGps(sb,admin);document.querySelector('#liveGpsStop').onclick=()=>stopGps(sb,admin);document.querySelector('#liveGpsRefresh').onclick=()=>renderAdmin(sb);if(admin){ensureMap();await renderAdmin(sb);pollTimer=setInterval(()=>renderAdmin(sb),10000);}window.addEventListener('beforeunload',()=>{if(pollTimer)clearInterval(pollTimer);});}
wait();
})();