(()=>{
const wait=()=>window.teamPaintServer?.client?install():setTimeout(wait,300);
let watchId=null, trackerId=localStorage.getItem('team-paint-tracker-id')||crypto.randomUUID();
localStorage.setItem('team-paint-tracker-id',trackerId);
let map=null,markers=new Map(),pollTimer=null,lastHistoryAt=0,lastHistoryPos=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const distanceM=(a,b)=>{if(!a||!b)return Infinity;const R=6371000,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x));};
function injectStyle(){const s=document.createElement('style');s.textContent=`
.live-gps{margin:14px 0;padding:14px;border:1px solid #d6dbe0;border-radius:16px;background:#fff}.live-gps h2{margin:0 0 4px}.live-gps-head{display:flex;gap:8px;align-items:center;justify-content:space-between;flex-wrap:wrap}.live-gps-actions{display:flex;gap:8px;flex-wrap:wrap}.live-gps-status{font-weight:800;padding:8px 0}.live-gps-status.on{color:#16753a}.live-gps-status.off{color:#8b5d00}#teamLiveMap{height:420px;border-radius:14px;overflow:hidden;background:#eef1f4;margin-top:10px}.team-live-list{display:grid;gap:8px;margin-top:10px}.team-live-card{border:1px solid #e0e4e7;border-radius:12px;padding:10px;background:#fafbfc}.team-live-card b{display:block}.team-live-meta{font-size:12px;opacity:.75;margin-top:3px}@media(max-width:600px){#teamLiveMap{height:330px}}
`;document.head.appendChild(s);}
function injectUi(){const main=document.querySelector('main');if(!main||document.querySelector('#liveGpsSection'))return;const section=document.createElement('section');section.id='liveGpsSection';section.className='live-gps';section.innerHTML=`<div class="live-gps-head"><div><h2>🛰️ GPS ـی ڕاستەوخۆی تیم</h2><small>شوێنی تیم لەکاتی کاردا</small></div><div class="live-gps-actions"><button id="liveGpsStart" class="primary" type="button">▶️ دەستپێکردنی Live GPS</button><button id="liveGpsStop" class="danger" type="button">⏹ کۆتایی GPS</button><button id="liveGpsRefresh" class="secondary" type="button">🔄 نوێکردنەوە</button></div></div><div id="liveGpsStatus" class="live-gps-status off">GPS ناچالاکە</div><div id="teamLiveMap"></div><div id="teamLiveList" class="team-live-list"></div>`;const anchor=document.querySelector('.archive')||main.lastElementChild;main.insertBefore(section,anchor);}
function status(t,on=false){const e=document.querySelector('#liveGpsStatus');if(e){e.textContent=t;e.className='live-gps-status '+(on?'on':'off');}}
async function profile(sb,user){const {data}=await sb.from('profiles').select('full_name,role').eq('id',user.id).maybeSingle();return data||{full_name:'',role:'worker'};}
async function publishPosition(sb,user,p){const prof=await profile(sb,user),teamName=prof.full_name?`تیمی بۆیاخ — ${prof.full_name}`:'تیمی بۆیاخ';const c=p.coords,row={tracker_id:trackerId,user_id:user.id,team_name:teamName,latitude:c.latitude,longitude:c.longitude,accuracy_m:Number.isFinite(c.accuracy)?c.accuracy:null,speed_mps:Number.isFinite(c.speed)?c.speed:null,heading_deg:Number.isFinite(c.heading)?c.heading:null,is_active:true,updated_at:new Date().toISOString()};const {error}=await sb.from('live_team_locations').upsert(row,{onConflict:'tracker_id'});if(error)throw error;const now=Date.now(),pos={lat:c.latitude,lng:c.longitude};if(now-lastHistoryAt>=30000||distanceM(lastHistoryPos,pos)>=15){const {error:hErr}=await sb.from('team_location_history').insert({tracker_id:trackerId,user_id:user.id,team_name:teamName,latitude:c.latitude,longitude:c.longitude,accuracy_m:Number.isFinite(c.accuracy)?c.accuracy:null});if(!hErr){lastHistoryAt=now;lastHistoryPos=pos;}}status(`🟢 GPS چالاکە — دوا نوێکردنەوە: ${new Date().toLocaleTimeString('ckb-IQ')}`,true);await render(sb);}
async function startGps(sb){const {data:{user}}=await sb.auth.getUser();if(!user)return alert('سەرەتا لە ☁️ سێرڤەر بچۆ ژوورەوە.');if(!navigator.geolocation)return alert('GPS لەم ئامێرەدا بەردەست نییە.');if(watchId!==null)return alert('Live GPS پێشتر چالاکە.');status('داواکاری ڕێگەپێدانی Location...');watchId=navigator.geolocation.watchPosition(p=>publishPosition(sb,user,p).catch(e=>{console.error(e);status('هەڵە لە ناردنی GPS');}),e=>{watchId!==null&&navigator.geolocation.clearWatch(watchId);watchId=null;status('ڕێگەی Location نەدرا یان GPS بەردەست نییە');alert('ڕێگەپێدانی Location/GPS بپشکنە و Allow بکە.');},{enableHighAccuracy:true,maximumAge:5000,timeout:20000});}
async function stopGps(sb){if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null;}const {data:{user}}=await sb.auth.getUser();if(user)await sb.from('live_team_locations').update({is_active:false,updated_at:new Date().toISOString()}).eq('tracker_id',trackerId).eq('user_id',user.id);status('⏹ GPS وەستێنرا');await render(sb);}
function ensureMap(){if(map||!window.L)return;map=L.map('teamLiveMap',{zoomControl:true}).setView([35.5613,45.4309],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);}
function ageText(ts){const s=Math.max(0,Math.round((Date.now()-new Date(ts).getTime())/1000));if(s<60)return `${s} چرکە پێش ئێستا`;const m=Math.round(s/60);return `${m} خولەک پێش ئێستا`;}
async function render(sb){ensureMap();const list=document.querySelector('#teamLiveList');if(!list)return;const {data,error}=await sb.from('live_team_locations').select('*').order('updated_at',{ascending:false});if(error){list.innerHTML='<div class="team-live-card">ناتوانرێت شوێنی تیم بخوێندرێتەوە.</div>';return;}const rows=data||[],seen=new Set(),bounds=[];for(const r of rows){seen.add(r.tracker_id);const ll=[r.latitude,r.longitude];bounds.push(ll);let m=markers.get(r.tracker_id);const popup=`<b>${esc(r.team_name)}</b><br>${r.is_active?'🟢 چالاک':'⚪ وەستاو'}<br>${esc(ageText(r.updated_at))}`;if(!m){m=L.marker(ll).addTo(map);markers.set(r.tracker_id,m);}else m.setLatLng(ll);m.bindPopup(popup);}for(const [id,m] of markers){if(!seen.has(id)){map.removeLayer(m);markers.delete(id);}}if(bounds.length===1)map.setView(bounds[0],16);else if(bounds.length>1)map.fitBounds(bounds,{padding:[30,30],maxZoom:16});list.innerHTML=rows.length?rows.map(r=>`<div class="team-live-card"><b>${r.is_active?'🟢':'⚪'} ${esc(r.team_name)}</b><div class="team-live-meta">${esc(ageText(r.updated_at))} · دقت: ${Math.round(r.accuracy_m||0)} m</div><div class="team-live-meta">${Number(r.latitude).toFixed(6)}, ${Number(r.longitude).toFixed(6)}</div></div>`).join(''):'<div class="team-live-card">هێشتا هیچ تیمێک Live GPS ـی دەست پێنەکردووە.</div>';}
async function install(){injectStyle();injectUi();const sb=window.teamPaintServer.client;document.querySelector('#liveGpsStart').onclick=()=>startGps(sb);document.querySelector('#liveGpsStop').onclick=()=>stopGps(sb);document.querySelector('#liveGpsRefresh').onclick=()=>render(sb);ensureMap();await render(sb);pollTimer=setInterval(()=>render(sb),10000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)render(sb);});window.addEventListener('beforeunload',()=>{if(pollTimer)clearInterval(pollTimer);});}
wait();
})();