(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const wait=()=>window.teamPaintServer?.client&&window.teamPaintDevice?init():setTimeout(wait,250);
let memberMode=false,records=[];
function style(){if(document.querySelector('#memberAccessStyle'))return;const s=document.createElement('style');s.id='memberAccessStyle';s.textContent=`
.member-mode #dailyPage,.member-mode .bookbar,.member-mode .archive,.member-mode .compact-stats,.member-mode .settings,.member-mode #assistantBtn,.member-mode #roleDashboard{display:none!important}.member-view{margin:14px 0;padding:14px;border:1px solid #d6dbe0;border-radius:16px;background:#fff}.member-view.hidden{display:none}.member-head{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap}.member-badge{padding:7px 10px;border-radius:999px;background:#eef3f7;font-weight:800}.member-list{display:grid;gap:10px;margin-top:12px}.member-card{border:1px solid #e1e5e8;border-radius:12px;padding:12px;background:#fafbfc}.member-card h3{margin:0 0 6px}.member-meta{font-size:13px;opacity:.78;line-height:1.7}.member-details{margin-top:10px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.member-details div{padding:8px;border-radius:9px;background:#fff;border:1px solid #eceff1}.member-photos{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:10px}.member-photos img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:10px;border:1px solid #ddd}.member-empty{padding:18px;text-align:center;border:1px dashed #ccd3d8;border-radius:12px}.member-search{width:100%;padding:12px;border:1px solid #ccd3d8;border-radius:10px;font-size:16px;margin-top:10px}@media(max-width:650px){.member-details{grid-template-columns:1fr}.member-photos{grid-template-columns:1fr}}
`;document.head.appendChild(s);}
function ui(){const main=document.querySelector('main');if(!main||document.querySelector('#memberView'))return;const sec=document.createElement('section');sec.id='memberView';sec.className='member-view hidden';sec.innerHTML=`<div class="member-head"><div><h2>👁️ بینینی داتاکانی تیم</h2><small>بەکارهێنەری ئەندام — تەنها بینین و Location</small></div><span class="member-badge">پارێزراو</span></div><input id="memberSearch" class="member-search" placeholder="گەڕان بە شوێن، بەروار یان ژمارەی تۆمار"><div id="memberList" class="member-list"></div>`;const anchor=document.querySelector('#liveGpsSection')||main.firstElementChild;main.insertBefore(sec,anchor);document.querySelector('#memberSearch').oninput=render;}
async function isAdmin(){const sb=window.teamPaintServer.client;const {data:{user}}=await sb.auth.getUser();if(!user)return false;const {data}=await sb.from('profiles').select('role').eq('id',user.id).maybeSingle();return data?.role==='admin';}
function mapRecord(r){return{id:r.id,recordNo:r.record_no||'',date:r.work_date||'',startTime:r.start_time||'',endTime:r.end_time||'',location:r.location||'',type:r.work_type||'',paintType:r.paint_type||'',color:r.color||'',length:Number(r.length_m||0),width:Number(r.width_cm||0),area:Number(r.area_m2||0),lat:r.latitude??'',lng:r.longitude??'',staff:r.staff||'',equipment:r.equipment||'',note:r.note||'',status:r.status||'',materials:r.record_materials||[],photos:r.record_photos||[]};}
async function load(){if(!memberMode||!window.teamPaintDevice.registered)return;const list=document.querySelector('#memberList');if(list)list.innerHTML='<div class="member-empty">داتا بار دەکرێت...</div>';try{const j=await window.teamPaintDevice.api('records');records=(j.records||[]).map(mapRecord);render();}catch(e){console.error(e);if(list)list.innerHTML='<div class="member-empty">پەیوەندی بە سێرڤەر سەرکەوتوو نەبوو.</div>';}}
function render(){if(!memberMode)return;const q=(document.querySelector('#memberSearch')?.value||'').trim().toLowerCase();const rs=records.filter(r=>!q||[r.date,r.recordNo,r.location,r.type,r.paintType,r.color,r.note].join(' ').toLowerCase().includes(q));const list=document.querySelector('#memberList');if(!list)return;list.innerHTML=rs.length?rs.map(r=>{const mats=(r.materials||[]).length?`<div><b>ماددە:</b> ${(r.materials||[]).map(m=>`${esc(m.name)} ${Number(m.quantity||0)} ${esc(m.unit||'')}`).join(' · ')}</div>`:'';const photos=(r.photos||[]).filter(p=>p.url).map(p=>`<a href="${esc(p.url)}" target="_blank" rel="noopener"><img src="${esc(p.url)}" alt="وێنەی کار"></a>`).join('');return `<article class="member-card"><h3>${esc(r.location||'شوێن دیاری نەکراوە')}</h3><div class="member-meta">${esc(r.date)} · ${esc(r.recordNo)} · ${esc(r.status)}</div><div class="member-details"><div><b>جۆری کار:</b> ${esc(r.type)}</div><div><b>جۆری بۆیاخ:</b> ${esc(r.paintType)}</div><div><b>ڕەنگ:</b> ${esc(r.color)}</div><div><b>درێژی:</b> ${r.length.toFixed(1)} m</div><div><b>پانی:</b> ${r.width.toFixed(1)} cm</div><div><b>ڕووبەر:</b> ${r.area.toFixed(1)} m²</div>${r.staff?`<div><b>تیم:</b> ${esc(r.staff)}</div>`:''}${r.equipment?`<div><b>ئامێر:</b> ${esc(r.equipment)}</div>`:''}${r.note?`<div><b>تێبینی:</b> ${esc(r.note)}</div>`:''}${mats}</div>${photos?`<div class="member-photos">${photos}</div>`:''}</article>`;}).join(''):'<div class="member-empty">هیچ داتایەک نەدۆزرایەوە.</div>';}
async function init(){style();ui();const admin=await isAdmin();if(admin){document.documentElement.classList.add('admin-mode');window.teamPaintAccess={role:'admin'};return;}memberMode=true;document.documentElement.classList.add('member-mode');document.querySelector('#memberView').classList.remove('hidden');window.teamPaintAccess={role:'member',reload:load};if(window.teamPaintDevice.registered)await load();window.addEventListener('team-paint-device-ready',load);setInterval(()=>{if(!document.hidden)load();},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});}
wait();
})();